version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest

    working_directory: ~/fog-node-discovery

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda env create -f environment.yml

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            conda init bash
            conda activate fog-node-discovery
            flake8 --statistics
            pytest -v --cov